name: Docker Image CI

on:
  push:
    branches: ["master"]

jobs:
  dockerhab_books:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build docker
        run: docker build . --file Dockerfile -t kristy27/micro-books-service:latest

      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push tag to Docker Hub
        run: docker push kristy27/micro-books-service:latest